# Generated by Django 3.0.8 on 2020-07-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category name(e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Deck name', max_length=200)),
                ('description', models.CharField(blank=True, default='', help_text='Enter Deck Description', max_length=200)),
                ('status', models.CharField(blank=True, choices=[('o', 'Open'), ('f', 'Followers Only'), ('x', 'Private')], default='x', help_text='Deck privacy', max_length=1)),
                ('category', models.ManyToManyField(help_text='Select a categroy for this deck', to='decks.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=200)),
                ('back_text', models.CharField(max_length=200)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.Deck')),
            ],
        ),
    ]
