# Generated by Django 3.0.8 on 2020-07-27 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['last_modified']},
        ),
        migrations.AddField(
            model_name='deck',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Enter Deck Description'),
        ),
    ]
