# Generated by Django 3.0.8 on 2020-07-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20200727_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='category',
        ),
        migrations.AddField(
            model_name='deck',
            name='categories',
            field=models.ManyToManyField(help_text='Select a categroy for this deck', related_name='decks', to='decks.Category'),
        ),
    ]
