# Generated by Django 3.0.8 on 2020-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20200727_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select a categroy for this deck', related_name='decks', to='decks.Category'),
        ),
    ]
