# Generated by Django 3.0.8 on 2020-07-31 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_auto_20200728_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
