# Generated by Django 3.0.8 on 2020-08-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_auto_20200731_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
