"""added card relationship to user

Revision ID: 48aab2c97f22
Revises: 6752ad378456
Create Date: 2020-04-19 07:50:09.313801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48aab2c97f22'
down_revision = '6752ad378456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'user_id')
    # ### end Alembic commands ###
