# Generated by Django 3.0.8 on 2020-08-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200806_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='followed_id',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
