# Generated by Django 3.0.8 on 2020-08-06 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200806_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('follower_id', 'followed_id')},
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
